### ISSUE TITLE
Compilation error with TypeScript 4.9.5

### ISSUE THREAD

**Issue by Loginov-Sergei** [vovaspace/brandi#35]
We use brandi@5.0.0 in our project and it worked well with TypeScript@4.6.4. But recently we had to update TypeScript version up to 4.9.5 and now we are facing with the following compilation error:

> node_modules/.pnpm/brandi@5.0.0/node_modules/brandi/lib/typings/types.d.ts:5:70 - error TS2344: Type 'T' does not satisfy the constraint 'object'.
> 
> 5 export declare type UnknownCreator<T = unknown> = UnknownConstructor<T> | UnknownFunction<T>;
>                                                                        ~
> 
>   node_modules/.pnpm/brandi@5.0.0/node_modules/brandi/lib/typings/types.d.ts:5:36
>     5 export declare type UnknownCreator<T = unknown> = UnknownConstructor<T> | UnknownFunction<T>;
>                                          ~~~~~~~~~~~
>     This type parameter might need an `extends object` constraint.
> 

Could you fix it?
